# Generated by Django 4.2.7 on 2023-11-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
